package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Jogador;

public class FrmPontuacao extends javax.swing.JFrame {

    /**
     * Creates new form FrmPontuacao
     * @param pontuacao
     */
    public FrmPontuacao(String pontuacao) {
        initComponents();
        lblPontuacao.setText(pontuacao);
        txtNome.setTransferHandler(null);
        new funcoesNecessariasTodosFormularios(this).setIconeFormulario();
        new funcoesNecessariasTodosFormularios(this).setCorBackgroundFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSPF = new javax.swing.JLabel();
        lblPontuacao = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPontuacao = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(464, 411));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSPF.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        lblSPF.setForeground(new java.awt.Color(206, 197, 21));
        lblSPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSPF.setText("Sua pontuação foi");
        getContentPane().add(lblSPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, -1));

        lblPontuacao.setFont(new java.awt.Font("Helvetica", 1, 70)); // NOI18N
        lblPontuacao.setForeground(new java.awt.Color(255, 255, 255));
        lblPontuacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontuacao.setText("0000");
        getContentPane().add(lblPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 460, -1));

        lblNome.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        lblNome.setForeground(new java.awt.Color(206, 197, 21));
        lblNome.setText("Insira seu nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 30));

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 140, 30));

        btnPontuacao.setBackground(new java.awt.Color(254, 254, 254));
        btnPontuacao.setFont(new java.awt.Font("Helvetica", 1, 15)); // NOI18N
        btnPontuacao.setText("Salvar Pontuação");
        btnPontuacao.setMaximumSize(new java.awt.Dimension(106, 38));
        btnPontuacao.setMinimumSize(new java.awt.Dimension(106, 38));
        btnPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontuacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, 40));

        btnMenu.setBackground(new java.awt.Color(254, 254, 254));
        btnMenu.setFont(new java.awt.Font("Helvetica", 1, 15)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 90, 31));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontuacaoActionPerformed
        Jogador jogador = criarJogador(txtNome.getText(), lblPontuacao.getText());   
        cadastrarJogador(jogador);
    }//GEN-LAST:event_btnPontuacaoActionPerformed

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if(txtNome.getText().length() >= 20 && !evt.isControlDown() && evt.getKeyCode() != KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_txtNomeKeyTyped

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        abrirMenu();
    }//GEN-LAST:event_btnMenuActionPerformed
    
    // Cria o objeto jogador
    private Jogador criarJogador(String nome, String pontuacao) {
        Jogador jogador = new Jogador();
        jogador.setNome(nome);
        jogador.setPontuacao(Integer.parseInt(pontuacao));
        
        return jogador;
    }
    
    // Verifica se o jogador foi inserido com sucesso no banco 
    private void cadastrarJogador(Jogador jogador) {
        if (jogador.inserir()) {
            JOptionPane.showMessageDialog(this, "Nome cadastrado com Sucesso!");
            abrirMenu();

        }
        else
            JOptionPane.showMessageDialog(this, jogador.getMensagemDeErro(), "Atenção", 1);

    }
    
    // Abre o formulário de Menu
    private void abrirMenu() {
        new FrmMenu().setVisible(true);
        this.setVisible(false);
    }
    
    // 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPontuacao().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPontuacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPontuacao;
    private javax.swing.JLabel lblSPF;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
