package view;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Ranking;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

public class FrmRanking extends javax.swing.JFrame {

    /**
     * Creates new form FrmRanking
     */
    public FrmRanking() {
        initComponents();
        new funcoesNecessariasTodosFormularios(this).setIconeFormulario();
        new funcoesNecessariasTodosFormularios(this).setCorBackgroundFormulario();
        carregarRanking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRanking = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        lblData1 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblPonto1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblPonto2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblData3 = new javax.swing.JLabel();
        lblNome3 = new javax.swing.JLabel();
        lblPonto3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblData4 = new javax.swing.JLabel();
        lblNome4 = new javax.swing.JLabel();
        lblPonto4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lblData5 = new javax.swing.JLabel();
        lblNome5 = new javax.swing.JLabel();
        lblPonto5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lblData6 = new javax.swing.JLabel();
        lblNome6 = new javax.swing.JLabel();
        lblPonto6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lblData7 = new javax.swing.JLabel();
        lblNome7 = new javax.swing.JLabel();
        lblPonto7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lblData8 = new javax.swing.JLabel();
        lblNome8 = new javax.swing.JLabel();
        lblPonto8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lblData9 = new javax.swing.JLabel();
        lblNome9 = new javax.swing.JLabel();
        lblPonto9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lblData10 = new javax.swing.JLabel();
        lblNome10 = new javax.swing.JLabel();
        lblPonto10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(464, 411));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRanking.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        lblRanking.setForeground(new java.awt.Color(206, 197, 21));
        lblRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRanking.setText("RANKING");
        getContentPane().add(lblRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 500, -1));

        lbl1.setBackground(new java.awt.Color(255, 215, 0));
        lbl1.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl1.setForeground(new java.awt.Color(206, 197, 21));
        lbl1.setText("1º -");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        btnMenu.setBackground(new java.awt.Color(254, 254, 254));
        btnMenu.setFont(new java.awt.Font("Helvetica", 1, 15)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.setMaximumSize(new java.awt.Dimension(106, 38));
        btnMenu.setMinimumSize(new java.awt.Dimension(106, 38));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 110, 40));

        lblData1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData1.setForeground(new java.awt.Color(255, 255, 255));
        lblData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData1.setText("--/--/----  --:--:--");
        getContentPane().add(lblData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 170, -1));

        btnImprimir.setBackground(new java.awt.Color(254, 254, 254));
        btnImprimir.setFont(new java.awt.Font("Helvetica", 1, 15)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 110, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(206, 197, 21));
        jLabel1.setText("Data Pontuação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(206, 197, 21));
        jLabel2.setText("Nome do Jogador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(206, 197, 21));
        jLabel3.setText("Pontos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        lblNome1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(255, 255, 255));
        lblNome1.setText("-----");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        lblPonto1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto1.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto1.setText("----");
        getContentPane().add(lblPonto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 40, -1));

        lbl2.setBackground(new java.awt.Color(255, 215, 0));
        lbl2.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl2.setForeground(new java.awt.Color(206, 197, 21));
        lbl2.setText("2º -");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        lblData2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData2.setForeground(new java.awt.Color(255, 255, 255));
        lblData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData2.setText("--/--/----  --:--:--");
        getContentPane().add(lblData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 170, -1));

        lblNome2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(255, 255, 255));
        lblNome2.setText("-----");
        getContentPane().add(lblNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        lblPonto2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto2.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto2.setText("----");
        getContentPane().add(lblPonto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 40, -1));

        lbl3.setBackground(new java.awt.Color(255, 215, 0));
        lbl3.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl3.setForeground(new java.awt.Color(206, 197, 21));
        lbl3.setText("3º -");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        lblData3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData3.setForeground(new java.awt.Color(255, 255, 255));
        lblData3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData3.setText("--/--/----  --:--:--");
        getContentPane().add(lblData3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 170, -1));

        lblNome3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome3.setForeground(new java.awt.Color(255, 255, 255));
        lblNome3.setText("-----");
        getContentPane().add(lblNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        lblPonto3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto3.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto3.setText("----");
        getContentPane().add(lblPonto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 40, -1));

        lbl4.setBackground(new java.awt.Color(255, 215, 0));
        lbl4.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl4.setForeground(new java.awt.Color(206, 197, 21));
        lbl4.setText("4º -");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        lblData4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData4.setForeground(new java.awt.Color(255, 255, 255));
        lblData4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData4.setText("--/--/----  --:--:--");
        getContentPane().add(lblData4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 170, -1));

        lblNome4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome4.setForeground(new java.awt.Color(255, 255, 255));
        lblNome4.setText("-----");
        getContentPane().add(lblNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblPonto4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto4.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto4.setText("----");
        getContentPane().add(lblPonto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 40, -1));

        lbl5.setBackground(new java.awt.Color(255, 215, 0));
        lbl5.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl5.setForeground(new java.awt.Color(206, 197, 21));
        lbl5.setText("5º -");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        lblData5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData5.setForeground(new java.awt.Color(255, 255, 255));
        lblData5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData5.setText("--/--/----  --:--:--");
        getContentPane().add(lblData5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, -1));

        lblNome5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome5.setForeground(new java.awt.Color(255, 255, 255));
        lblNome5.setText("-----");
        getContentPane().add(lblNome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        lblPonto5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto5.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto5.setText("----");
        getContentPane().add(lblPonto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 40, -1));

        lbl6.setBackground(new java.awt.Color(255, 215, 0));
        lbl6.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl6.setForeground(new java.awt.Color(206, 197, 21));
        lbl6.setText("6º -");
        getContentPane().add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        lblData6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData6.setForeground(new java.awt.Color(255, 255, 255));
        lblData6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData6.setText("--/--/----  --:--:--");
        getContentPane().add(lblData6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 170, -1));

        lblNome6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome6.setForeground(new java.awt.Color(255, 255, 255));
        lblNome6.setText("-----");
        getContentPane().add(lblNome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lblPonto6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto6.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto6.setText("----");
        getContentPane().add(lblPonto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, -1));

        lbl7.setBackground(new java.awt.Color(255, 215, 0));
        lbl7.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl7.setForeground(new java.awt.Color(206, 197, 21));
        lbl7.setText("7º -");
        getContentPane().add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        lblData7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData7.setForeground(new java.awt.Color(255, 255, 255));
        lblData7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData7.setText("--/--/----  --:--:--");
        getContentPane().add(lblData7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, -1));

        lblNome7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome7.setForeground(new java.awt.Color(255, 255, 255));
        lblNome7.setText("-----");
        getContentPane().add(lblNome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        lblPonto7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto7.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto7.setText("----");
        getContentPane().add(lblPonto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 40, -1));

        lbl8.setBackground(new java.awt.Color(255, 215, 0));
        lbl8.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl8.setForeground(new java.awt.Color(206, 197, 21));
        lbl8.setText("8º-");
        getContentPane().add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 30));

        lblData8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData8.setForeground(new java.awt.Color(255, 255, 255));
        lblData8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData8.setText("--/--/----  --:--:--");
        getContentPane().add(lblData8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 170, -1));

        lblNome8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome8.setForeground(new java.awt.Color(255, 255, 255));
        lblNome8.setText("-----");
        getContentPane().add(lblNome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        lblPonto8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto8.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto8.setText("----");
        getContentPane().add(lblPonto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 40, -1));

        lbl9.setBackground(new java.awt.Color(255, 215, 0));
        lbl9.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl9.setForeground(new java.awt.Color(206, 197, 21));
        lbl9.setText("9º -");
        getContentPane().add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 30));

        lblData9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData9.setForeground(new java.awt.Color(255, 255, 255));
        lblData9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData9.setText("--/--/----  --:--:--");
        getContentPane().add(lblData9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 170, -1));

        lblNome9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome9.setForeground(new java.awt.Color(255, 255, 255));
        lblNome9.setText("-----");
        getContentPane().add(lblNome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        lblPonto9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto9.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto9.setText("----");
        getContentPane().add(lblPonto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 40, -1));

        lbl10.setBackground(new java.awt.Color(255, 215, 0));
        lbl10.setFont(new java.awt.Font("Helvetica", 0, 20)); // NOI18N
        lbl10.setForeground(new java.awt.Color(206, 197, 21));
        lbl10.setText("10º -");
        getContentPane().add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 30));

        lblData10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblData10.setForeground(new java.awt.Color(255, 255, 255));
        lblData10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData10.setText("--/--/----  --:--:--");
        getContentPane().add(lblData10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 170, -1));

        lblNome10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblNome10.setForeground(new java.awt.Color(255, 255, 255));
        lblNome10.setText("-----");
        getContentPane().add(lblNome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        lblPonto10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblPonto10.setForeground(new java.awt.Color(255, 255, 255));
        lblPonto10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto10.setText("----");
        getContentPane().add(lblPonto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 40, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new FrmMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        Ranking ranking = new Ranking();
        ArrayList<Ranking> lista = ranking.getRanking();
        
        try {
            JasperReport templateDoRelatorio;
            JasperPrint relatorioPreenchido;
            JasperViewer visualizadorDoRelatorio;
            
            // Carrega o template do relatório
            templateDoRelatorio = JasperCompileManager.compileReport("relatorios/relatorioRanking.jrxml");
            
            // Preenche o relatório com os dados do banco referente ao ranking
            relatorioPreenchido = JasperFillManager.fillReport(templateDoRelatorio, null, new JRBeanCollectionDataSource(lista));
            
            // Apresenta o relatório
            visualizadorDoRelatorio = new JasperViewer(relatorioPreenchido, false);
            visualizadorDoRelatorio.setVisible(true);
         
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na apresentação do relatório!");
        }
    }//GEN-LAST:event_btnImprimirActionPerformed
    
    // Popula o ranking com os nomes, pontuações e datas de criação da pontuação dos jogadores
    private void carregarRanking(){
        JLabel[] labelNomes = getLabelsNome();
        JLabel[] labelPontuacao = getLabelsPontuacao();
        JLabel[] labelDataCriacao = getLabelsDataCriacao();
        Ranking ranking = new Ranking();
        
        ArrayList<Ranking> jogadores = ranking.getRankingParcial();
        int i = 0;
        
        // Passa por todos o array list ranking populando os labels com cada "linha" da lista
        for (Ranking jogador : jogadores)
        {
            labelNomes[i].setText(jogador.getNome());
            labelPontuacao[i].setText(jogador.getPontuacao());
            labelDataCriacao[i].setText(jogador.getDataCriacao());

            i++;
        }
    }
    
    // Retorna os labels que apresentam o nome dos jogadores
    private JLabel[] getLabelsNome() {
        JLabel[] labelsNome = new JLabel[] {
            lblNome1, lblNome2, lblNome3,
            lblNome4, lblNome5, lblNome6,
            lblNome7, lblNome8, lblNome9,
            lblNome10 };
        
        return labelsNome;
    }
    
    // Retorna os labels que apresentam a pontuação dos jogadores
    private JLabel[] getLabelsPontuacao() {
        JLabel[] labelsPontuacao = new JLabel[] {
            lblPonto1, lblPonto2, lblPonto3,
            lblPonto4, lblPonto5, lblPonto6,
            lblPonto7, lblPonto8, lblPonto9,
            lblPonto10,
        };
        
        return labelsPontuacao;
    }
    
    // Retorna os labels que apresentam a data em que foi feito a pontuação dos jogadores
    private JLabel[] getLabelsDataCriacao() {
        JLabel[] labelsDataCriacao = new JLabel[] {
            lblData1, lblData2, lblData3,
            lblData4, lblData5, lblData6,
            lblData7, lblData8, lblData9,
            lblData10,
        };
        
        return labelsDataCriacao;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRanking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData10;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblData3;
    private javax.swing.JLabel lblData4;
    private javax.swing.JLabel lblData5;
    private javax.swing.JLabel lblData6;
    private javax.swing.JLabel lblData7;
    private javax.swing.JLabel lblData8;
    private javax.swing.JLabel lblData9;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome10;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblNome5;
    private javax.swing.JLabel lblNome6;
    private javax.swing.JLabel lblNome7;
    private javax.swing.JLabel lblNome8;
    private javax.swing.JLabel lblNome9;
    private javax.swing.JLabel lblPonto1;
    private javax.swing.JLabel lblPonto10;
    private javax.swing.JLabel lblPonto2;
    private javax.swing.JLabel lblPonto3;
    private javax.swing.JLabel lblPonto4;
    private javax.swing.JLabel lblPonto5;
    private javax.swing.JLabel lblPonto6;
    private javax.swing.JLabel lblPonto7;
    private javax.swing.JLabel lblPonto8;
    private javax.swing.JLabel lblPonto9;
    private javax.swing.JLabel lblRanking;
    // End of variables declaration//GEN-END:variables
}
